name: release_build

env: 
  CI: false

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install

      - name: Build the extension
        run: yarn run build

      - name: Pack built artifact
        run: zip -r -q -o chrome-extension-release.zip  build/

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          path: chrome-extension-release.zip
          if-no-files-found: error